apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  ports:
    - port: 9870
      name: web
    - port: 9000
      name: hdfs
  selector:
    app: namenode
---
apiVersion: v1
kind: Service
metadata:
  name: datanode
spec:
  ports:
    - port: 9864
      name: web
  selector:
    app: datanode
---
apiVersion: v1
kind: Service
metadata:
  name: resourcemanager
  namespace: data-platform
spec:
  ports:
    - port: 8088
      name: web
    - port: 8030
      name: scheduler
    - port: 8031
      name: tracker
    - port: 8032
      name: admin
  selector:
    app: resourcemanager
---
apiVersion: v1
kind: Service
metadata:
  name: nodemanager
spec:
  ports:
    - port: 8042
      name: web
  selector:
    app: nodemanager
---
apiVersion: v1
kind: Service
metadata:
  name: historyserver
spec:
  ports:
    - port: 8188
      name: web
    - port: 8190
      name: https
  selector:
    app: historyserver
