apiVersion: v1
kind: Service
metadata:
  name: spark-master
spec:
  ports:
    - name: master-ui
      port: 8080
      targetPort: 8080
    - name: master-port
      port: 7077
      targetPort: 7077
    - name: app-ui-1
      port: 4040
      targetPort: 4040
    - name: app-ui-2
      port: 4041
      targetPort: 4041
    - name: app-ui-3
      port: 4042
      targetPort: 4042
    - name: app-ui-4
      port: 4043
      targetPort: 4043
    - name: app-ui-5
      port: 4044
      targetPort: 4044
    - name: app-ui-6
      port: 4045
      targetPort: 4045
  selector:
    app: spark-master

---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
spec:
  ports:
    - port: 8083
      name: web
    - port: 8082
      name: worker
  selector:
    app: spark-worker
